language: php
php:
    - 7.2
    - 7.3
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
install:
    - composer validate
    - travis_retry composer install --no-interaction
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
